use_frameworks!
source "https://github.com/CocoaPods/Specs.git"
target 'RemoveBackGround_Example' do
  pod 'RemoveBackGround', :path => '../'

  target 'RemoveBackGround_Tests' do
    inherit! :search_paths

    
  end
end
